import pandas as pd

# Lê a planilha “Plan1” inteira em um DataFrame
df = pd.read_excel("Molde.xlsx", sheet_name=None)

print(df)  # mostra as primeiras linhas para confirmar

# 1) DataFrame de exemplo
nova_aba = pd.DataFrame(
    {
        "PACIENTE": [],
        "Ácido úrico": [],
        "Bilirrubina Total e Frações": [],
        "Colesterol total": [],
        "Colesterol HDL": [],
        "Colesterol LDL": [],
        "Creatinina": [],
        "Glicose - glicemia": [],
        "Insulina": [],
        "TGO -AST - Transaminase Oxalacetica": [],
        "TGP - ALT - Transaminase pirúvica": [],
        "Triglicerídeos": [],
        "Uréia": [],
        "ABO - Fator RH": [],
        "Hemograma completo": [],
        "Plaquetas": [],
        "TAP - Tempo de protrombina": [],
        "TS - Tempo de sangramento - DUKE": [],
        "ASLO - Antiestreptolisina": [],
        "Fator reumatóide  - FR - Látex": [],
        "PCR - Proteína C Reativa dosagem": [],
        "FTA - ABS IGG p Sífilis": [],
        "FTA - ABS IGM p Sífilis": [],
        "VDRL quantitativo - VDRL com titulação": [],
        "Hepatite A (HAV  IGM)": [],
        "Hepatite A (HAV  IGG)": [],
        "Hepatite B  - HBSAG": [],
        "Hepatite B - Anti HBS": [],
        "Hepatite B - Anti HBC IGM": [],
        "Hepatite B - HBEAG": [],
        "Hepatite C - Anti-HCV": [],
        "HIV 1 + HIV 2 (ELISA)": [],
        "Herpes simples IGG": [],
        "Herpes Simples IGM": [],
        "Folato - Ácido fólico - Vitamina B9": [],
        "Imunoglobulina E - IGE": [],
        "Beta-HCG - Gonadotrofina coriônica humana": [],
        "Parasitológico de Fezes - Pesquisa de ovos e cistos de parasitas - EPF": [],
        "Sumário de urina - EAS- Urina tipo 1": [],
        "Homocisteína na urina": [],
        "Urocultura antibiograma- Cultura de bactérias para identificação": [],
        "Cultura para BAAR - Micobactéria - Tuberculose": [],
        "Sódio - Na": [],
        "Potássio - k": [],
        "Cloreto - Cloro sérico": [],
        "Fosfatase alcalina - FA - FAL": [],
        "Proteínas Totais e Frações": [],
        "Alfa-fetoproteína": [],
        "Antitireoglobulina": [],
        "antimicrossomas": [],
        "T3 total (Triodotironina)": [],
        "T4 total - Tiroxina": [],
        "T4 livre - Tiroxina livre": [],
        "TSH - Hormônio tireoestimulante": [],
        "LH - Hormônio Luteinizante": [],
        "FSH - Hormônio Folículo estimulante": [],
        "GAMA GT - Gama glutamil transferase": [],
        "Progesterona": [],
        "PSA - Antígeno prostático específico": [],
        "Mucoproteínnas - GPA - Alfa 1 glicoproteína ácida": [],
        "Amilase": [],
        "Lipase": [],
        "Hba1C - Hemoglobina glicosilada - A1c": [],
        "Vitamina B12 - Cobalamina": [],
        "Vitamina D - 25 hidroxi D - 25OHD": [],
        "CEA - Antígeno Carcinoembrionário": [],
        "C3": [],
        "C4": [],
        "Cálcio": [],
        "Cortisol": [],
        "Capacidade de Fixação de Ferro": [],
        "TOTG - Curva Glicêmica": [],
        "CH50 - Complemento total": [],
        "Citomegalovírus IGM": [],
        "Citomegalovírus IGG": [],
        "Coombs Direto -TAD - Teste Direto de Antiglobulina Humana": [],
        "Coombs Indireto - TIA - Teste indireto de Antiglobulina Humana": [],
        "Epstein Barr IGG": [],
        "Epstein Barr IGM": [],
        "Eletroforese de hemoglobina": [],
        "Eletroforese de proteínas": [],
        "Estrona - E1": [],
        "Estradiol - Estrogênio": [],
        "FAN - Fator antinúcleo - Anticorpos antinúcleo": [],
        "Ferro sérico": [],
        "Ferritina": [],
        "Fibrinogênio": [],
        "Fósforo": [],
        "Desidrogenase lática - DHL - LDH": [],
        "Magnésio": [],
        "Microalbumina na urina": [],
        "Prolactina": [],
        "Paratormônio - PTH": [],
        "Reticulócitos": [],
        "Rubéola IGG": [],
        "Rubéola IGM": [],
        "Sangue oculto nas fezes": [],
        "Testosterona Total": [],
        "Testosterona livre": [],
        "Toxoplasmose IGM": [],
        "Toxoplasmose IGG": [],
        "Transferrina": [],
        "Tempo de tromboplastina p ativada - TTPA": [],
        "VHS - Velocidade de Hemossedimentação": [],
        "HTLV 1 + HTLV 2 (ELISA)": [],
        "HTLV 1 + HTLV 2 (WESTERN BLOT)": [],
        "Tempo de trombina": [],
        "G6PD - Glicose6 fostato desidrogenase": [],
        "Eritrograma (eritrócitos, hemoglobina, hematócritos)": [],
        "Hemoglobina": [],
        "Troponina": [],
        "Hematócrito": [],
        "PCR quantitativa - Proteína C Reativa quantitativa": [],
        "CPK - Creatinofosfoquinase": [],
        "CPK-MB": [],
        "Ionograma": [],
        "CPF": [],
        "SUS": [],
        "DATA DE NASCIMENTO": [],
        "TELEFONE": [],
        "POSTO": [],
        "PROFISSIONAL SOLICITANTE": [],
        "COLETA DOMICILIAR": [],
    }
)
titulo = "03-05"
# 2) Usa ExcelWriter em modo append
with pd.ExcelWriter("Pasta 1.xlsx", engine="openpyxl", mode="a") as writer:
    # 3) Grava como aba “Estoque” sem tocar nas outras
    nova_aba.to_excel(writer, sheet_name=titulo, index=False)
    # Se “Estoque” já existir, dará erro – basta escolher outro nome.
